offshore_wind: # electricity production, wind, 1-3MW turbine, offshore
  lca: 0.0164  # kgCO2e/kWh

ccgt: # electricity production, natural gas, combined cycle power plant
  lca: 0.384  # kgCO2e/kWh

onshore_wind(<1MW): # electricity production, wind, <1MW turbine, onshore
  lca: 0.0132  # kgCO2e/kWh

onshore_wind(>3MW): # electricity production, wind, >3MW turbine, onshore
  lca: 0.0229 # kgCO2e/kWh

onshore_wind(1-3MW): # electricity production, wind, 1-3MW turbine, onshore
  lca: 0.0140 # kgCO2e/kWh

biomass: # heat and power co-generation, wood chips, 6667 kW, state-of-the-art 2014
  lca: 0.0531  # kgCO2e/kWh

hydro: # electricity production, hydro, run-of-river
  lca: 0.00435 # kgCO2e/kWh

PV: # electricity production, photovoltaic, 570kWp open ground installation, multi-Si
  lca: 0.0803 # kgCO2e/kWh 
  
oil: # electricity production, oil
  lca: 1.41 # kgCO2e/kWh

nuclear: # electricity production, nuclear
  lca: 0.00690 # kgCO2e/kWh